### ISSUE TITLE
[feature request]Hashtag Selection 

### ISSUE THREAD

**Issue by commiyou** [ridvan/send-to-telegram#2]
thanks for creating the Send-to-Telegram Chrome extension!

**Comment by ridvan** [comment]
Hi @commiyou,

Can you provide more details on how adding hashtags should work? The first thing that comes to mind is that we can assign hashtags to domains via the dashboard. For example, when I send messages from "example.com," the hashtag #LinksFromExample can be added to the beginning or the end of the message. Also, if there's no specific match, we can use the domain name as the hashtag.

Thank you for the suggestion! ☺️

**Comment by commiyou** [comment]
I’m really glad to hear back from you! Here’s how I plan to use it: I’ll tag some content with #work for work tips and #fun for just-for-fun stuff. That way, I can easily search for them on Telegram using hashtags.

By the way, is it possible to preset a list of hashtags so that when I’m sharing content, a bubble pops up allowing me to choose? If I don’t make a choice within a certain time, the bubble disappears and it either adds a default hashtag or none at all, depending on the settings.

**Comment by ridvan** [comment]
Thanks for making it clear. I think this would be a great feature 👍🏻. Currently, the extension doesn't require any special permissions from the user. However, to implement the bubble feature, I would need to request additional permissions, such as scripting, which I have avoided so far. After deciding on an appropriate solution, I will work on this feature.

P.S. If I go for a workaround without asking for more permissions, I can handle the tags directly from the context menu like this (the options/nesting can change; I just made it up for now 😁):

![image](https://github.com/ridvan/send-to-telegram/assets/63660173/a3f840e8-4e8a-40e2-986e-aba4a364a9b1)

**Comment by ridvan** [comment]
Hi @commiyou,

I've added the hashtags feature to the extension. You can now add your hashtags from the settings page and use these tags on the context menu options. The update is available on Chrome Web Store and will soon be released on Edge Add-ons as well.

Thanks for your suggestion.
